### ISSUE TITLE
Latest release wasn't rebuilt before publishing

### ISSUE THREAD

**Issue by pgoldberg** [calebdwilliams/rollup-plugin-import-assert#10]
Wanted to call attention to the comment here: https://github.com/calebdwilliams/rollup-plugin-import-assert/pull/8#issuecomment-1292847070

Although the source code is up-to-date in the latest release, the rollup distribution isn't updated from the previous version. If you get the chance to rebuild it and publish I'd really appreciate it!

**Comment by mfedderly** [comment]
@calebdwilliams any chance you can get some time to do a fixed release? Thanks!

**Comment by calebdwilliams** [comment]
Apologies, the fix should be in `rollup-plugin-import-assert@2.1.3`

**Comment by pgoldberg** [comment]
Thank you! Confirmed this is fixed now 🙂
