### ISSUE TITLE
Does not work with node 12

### ISSUE THREAD

**Issue by adrelino** [calebdwilliams/rollup-plugin-import-assert#6]
For node 12, fails with:
```
./node_modules/rollup-plugin-import-assert/dist/import-assert.cjs:89
const assert = { type: node.arguments[0].properties[0]?.value?.properties[0].value.value };
SyntaxError: Unexpected token '.'
```
with node 14 and 16 it works.
Problem is I have a server with Debian 11.3 that only comes with node 12 and I cannot upgrade

**Comment by calebdwilliams** [comment]
Sorry I'm just now seeing this. I got pretty burnt out and am finally feeling back in it. Is this still an issue for you?

**Comment by calebdwilliams** [comment]
Closing due to lack of response. Also node@12 is a bit old for me to worry about here.

**Comment by adrelino** [comment]
Thanks, we ended up circumventing the problem by just importing js instead of json. That also solved another dev issue of ours, namely that Firefox still does not natively support import assertions. And you are right, node 12 is too old to care. More important in the future might be compatibility with Rollup 3 that got recently released.
