### ISSUE TITLE
assert svg

### ISSUE THREAD

**Issue by ghost** [calebdwilliams/rollup-plugin-import-assert#9]
i know this follows the assertion spec closely, but i was curious with the use of template literals if this could be opened up for `assert: {type: 'svg'}`

**Comment by calebdwilliams** [comment]
I think I'd prefer to leave the plugin to meet currently-specced assertion semantics so we don't accidentally break or block future behavior. I did consider adding an option like `dangerouslyAllowNonStandardModuleTypes`, but have decided against it. It's probably a better idea to just do this another way although I do hope import assertions do eventually allow behavior like this.
